logging:
  receivers:
    webapp-receiver:
      type: files
      include_paths:
        - /var/log/webapp/webapp.log
      record_log_file_path: true
  processors:
    webapp-processor:
      type: parse_json
      time_key: time
      time_format: "YYYY-MM-DDTHH:MM:SS.sssZ"
    move_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
          map_values:
            "debug": "DEBUG"
            "info": "INFO"
            "warn": "WARNING"
            "error": "ERROR"
            "fatal": "FATAL"
  service:
    pipelines:
      default_pipeline:
        receivers: [webapp-receiver]
        processors:
          - webapp-processor
          - move_severity