name: Build Packer Machine Image

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Zip application code
      run: |
        # Change directory to the root of the repository
        cd .

        # Zip the entire repository
        zip -r webapp.zip .

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with: 
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Install Packer
      run: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install packer

    - name: Initiate Packer template
      run: packer init -var-file=./packer/variables.json ./packer

    - name: Validate Packer template
      run: packer validate -var-file=./packer/variables.json ./packer

    - name: Build Packer template
      run: packer build -var-file=./packer/variables.json ./packer

    - name: Create Instance template
      run: |
        gcloud compute instance-templates create test3 --source-instance=webapp-instance-0b1g --source-instance-zone=us-central1-b --instance-template-region=us-central1 --configure-disk=device-name=persistent-disk-0,instantiate-from=custom-image,custom-image=projects/preeticloud/global/images/custom-image-1712176719,auto-delete=yes