name: Build Packer Machine Image

on:
  pull_request:
    types: [ closed ]
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Zip application code
      run: |
        # Change directory to the root of the repository
        cd .

        # Zip the entire repository
        zip -r webapp.zip .

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with: 
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Install Packer
      run: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install packer

    - name: Initiate Packer template
      run: packer init -var-file=./packer/variables.json ./packer

    - name: Validate Packer template
      run: packer validate -var-file=./packer/variables.json ./packer

    - name: Build Packer template
      run: | 
        PACKER_OUTPUT=$(packer build -var-file=./packer/variables.json ./packer 2>&1)
        CUSTOM_IMAGE_ID=$(echo "$PACKER_OUTPUT" | grep -oP "custom-image-\d+")
        echo "Custom Image ID: $CUSTOM_IMAGE_ID"
        TIMESTAMP=$(date +"%d%H%M%S")
        gcloud compute instance-templates create instance-temp-${TIMESTAMP} --source-instance=webapp-instance-${{secrets.INSTANCE_EXT}} --source-instance-zone=us-central1-b --instance-template-region=us-central1 --configure-disk=device-name=persistent-disk-0,instantiate-from=custom-image,custom-image=projects/preeticloud/global/images/$CUSTOM_IMAGE_ID,auto-delete=yes

        gcloud compute instance-groups managed set-instance-template instance-group-igm --template=projects/preeticloud/regions/us-central1/instanceTemplates/instance-temp-${TIMESTAMP} --region=us-central1

        gcloud compute instance-groups managed rolling-action start-update instance-group-igm --version=template=projects/preeticloud/regions/us-central1/instanceTemplates/instance-temp-${TIMESTAMP} --region=us-central1
        
    - name: Wait for Instance Refresh
      run: |
        gcloud compute instance-groups managed wait-until instance-group-igm --version-target-reached