name: HCL Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y packer

    - name: Format Packer template
      run: packer fmt -check -var-file=variables.json gcp-ami.pkr.hcl

    - name: Validate Packer template
      run: packer validate -var-file=variables.json gcp-ami.pkr.hcl
