name: HCL Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y packer
    
    - name: Zip all the webApp files
      run: |
          zip -r webapp.zip ./
          pwd

    - name: Setup Environment File
      run: |
          cat << EOF > .env
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }} 
          EOF
      shell: bash

    - name: Initialize Packer (install required plugins)
      run: packer init ./packer/gcp-ami.pkr.hcl

    - name: Format Packer template
      run: set -e
          packer fmt -var-file=./packer/variables.json ./packer/gcp-ami.pkr.hcl || exit 1

    - name: Validate Packer template
      run: packer validate -var-file=./packer/variables.json ./packer/gcp-ami.pkr.hcl || exit 1