name: HCL Packer Validation

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Packer
      run: |
        sudo apt-get update
        sudo apt-get install -y packer
    
    - name: Zip all the webapp files
      run: |
          zip -r webapp.zip ./
          pwd

    - name: Initialize Packer (install required plugins)
      run: packer init ./packer/gcp-ami.pkr.hcl

    - name: Format Packer template
      run: set -e
          packer fmt -var-file=./packer/variables.json ./packer/gcp-ami.pkr.hcl || exit 1

    - name: Validate Packer template
      run: packer validate -var-file=./packer/variables.json ./packer/gcp-ami.pkr.hcl || exit 1